include::../shared-doc/attributes.adoc[]

= helloworld-mdb: Helloworld Using an MDB (Message-Driven Bean)
:author: Serge Pagop, Andy Taylor, Jeff Mesnil
:level: Intermediate
:technologies: JMS, EJB, MDB

[abstract]
The `helloworld-mdb` quickstart uses JMS and EJB Message-Driven Bean (MDB) to create and deploy JMS topic and queue resources in {productName}.

:standalone-server-type: full
:archiveType: war

//*************************************************
// Shared CD and Product Release content
//*************************************************

== What is it?

The `helloworld-mdb` quickstart demonstrates the use of remote AMQ cluster as a message broker for the clients deployed in EAP (Message Driven Beans and JMS Producers)

This project creates two JMS resources:

* TestQueue
* testTopic


// Additional deployment information
Look at the EAP console or server log and you should see log messages corresponding to the deployment of the message-driven beans and the instantiation the JMS destinations:

[source,options="nowrap"]
----
...
15:25:44,402 INFO  [org.jboss.as.ejb3] (MSC service thread 1-2) WFLYEJB0042: Started message driven bean 'HelloWorldQTopicMDB' with 'activemq-ra' resource adapter
15:25:44,405 INFO  [org.jboss.as.ejb3] (MSC service thread 1-4) WFLYEJB0042: Started message driven bean 'HelloWorldQueueMDB' with 'activemq-ra' resource adapter
15:25:44,710 INFO  [org.apache.activemq.artemis.ra] (default-threads - 5) AMQ151004: Instantiating javax.jms.Queue "TestQueue" directly since UseJNDI=false.
15:25:44,737 INFO  [org.apache.activemq.artemis.ra] (default-threads - 6) AMQ151004: Instantiating javax.jms.Topic "testTopic" directly since UseJNDI=false.

----

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/ and will send some messages to the queue.

To send messages to the topic, use the following URL: http://localhost:8080/{artifactId}/HelloWorldMDBServletClient?topic

== Investigate the Server Console Output

Look at the {productName} console or Server log and you should see log messages like the following:

[source,options="nowrap"]
----
INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-9 (ActiveMQ-client-global-threads-1189700957)) Received Message from queue: This is message 5
INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-6 (ActiveMQ-client-global-threads-1189700957)) Received Message from queue: This is message 1
INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-7 (ActiveMQ-client-global-threads-1189700957)) Received Message from queue: This is message 4
INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-5 (ActiveMQ-client-global-threads-1189700957)) Received Message from queue: This is message 2
INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-4 (ActiveMQ-client-global-threads-1189700957)) Received Message from queue: This is message 3
----

== EAP configuration
* Create outbound socket bindings for all the masters
[source xml,options="nowrap"]
----
<outbound-socket-binding name="messaging-remote-master1">
            <remote-destination host="localhost" port="61616"/>
        </outbound-socket-binding>
        <outbound-socket-binding name="messaging-remote-master2">
            <remote-destination host="localhost" port="61617"/>
        </outbound-socket-binding>
----
* Create remote connectors that will use those bindings

[source xml,options="nowrap"]
----
                <remote-connector name="netty-remote-master1" socket-binding="messaging-remote-master1"/>
                <remote-connector name="netty-remote-master2" socket-binding="messaging-remote-master2"/>
----

* Create a pooled connection factory using these connectors

[source xml,options="nowrap"]
----
             <pooled-connection-factory name="activemq-ra" entries="java:/Amq7CF" connectors="netty-remote-master1 netty-remote-master2" ha="true" reconnect-attempts="-1" user="admin" password="admin" initial-connect-attempts="-1" statistics-enabled="true">
----

* Make sure that the resource adapter name matches the name of the pooled connection factory, if you already have a pooled connection factory with this name then rename it.

[source xml,options="nowrap"]
----
                            <mdb>
                           <resource-adapter-ref resource-adapter-name="${ejb.resource-adapter-name:activemq-ra}"/>
                           <bean-instance-pool-ref pool-name="mdb-strict-max-pool"/>
                       </mdb>
----